{"name": "test_fixture_zcc2[cc_calculator_shuju0]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1.5 == 6\n  +1.5\n  -6", "trace": "self = <cc_work.test_fixture_zcc.TestCal_cc_new object at 0x00000000039DA3C8>, cc_calculator_func = <cc_work.calculator_cc.Calculator object at 0x00000000039DAB00>, cc_calculator_shuju = [3, 2, 6]\n\n    @pytest.mark.run(order=4)\n    def test_fixture_zcc2(self, cc_calculator_func, cc_calculator_shuju):\n        result = cc_calculator_func.div(cc_calculator_shuju[0], cc_calculator_shuju[1])\n        print('这是测试用例2')\n        # print(result)\n>       assert result == cc_calculator_shuju[2]\nE       assert 1.5 == 6\nE         +1.5\nE         -6\n\ntest_fixture_zcc.py:32: AssertionError"}, "parameters": [{"name": "cc_calculator_shuju", "value": "[3, 2, 6]"}], "start": 1609398358082, "stop": 1609398358083, "uuid": "6fc5de6e-e798-42b5-a741-45c8e42a9482", "historyId": "9dedc9ada93b293aa622ae15533b1da7", "testCaseId": "6207987451ade26d46e5eac58d4c08e9", "fullName": "test_fixture_zcc.TestCal_cc_new#test_fixture_zcc2", "labels": [{"name": "suite", "value": "test_fixture_zcc"}, {"name": "subSuite", "value": "TestCal_cc_new"}, {"name": "host", "value": "admin-PC"}, {"name": "thread", "value": "12680-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_fixture_zcc"}]}