{"name": "test_fixture_zcc4[cc_calculator_shuju2]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1000000 == 2000\n  +1000000\n  -2000", "trace": "self = <cc_work.test_fixture_zcc.TestCal_cc_new object at 0x00000000039B4EB8>, cc_calculator_func = <cc_work.calculator_cc.Calculator object at 0x00000000039ABAC8>, cc_calculator_shuju = [1000, 1000, 2000]\n\n    @pytest.mark.run(order=3)\n    def test_fixture_zcc4(self, cc_calculator_func, cc_calculator_shuju):\n        result = cc_calculator_func.mul(cc_calculator_shuju[0], cc_calculator_shuju[1])\n        print('这是测试用例4')\n        # print(result)\n>       assert result == cc_calculator_shuju[2]\nE       assert 1000000 == 2000\nE         +1000000\nE         -2000\n\ntest_fixture_zcc.py:46: AssertionError"}, "parameters": [{"name": "cc_calculator_shuju", "value": "[1000, 1000, 2000]"}], "start": 1609398358029, "stop": 1609398358030, "uuid": "d3b8a11f-57e8-4973-a39f-b571e0d86be5", "historyId": "a7158f0a316d7c94883159c83077ccb3", "testCaseId": "000433c5f8a90c3b0946db3d61bfc89d", "fullName": "test_fixture_zcc.TestCal_cc_new#test_fixture_zcc4", "labels": [{"name": "suite", "value": "test_fixture_zcc"}, {"name": "subSuite", "value": "TestCal_cc_new"}, {"name": "host", "value": "admin-PC"}, {"name": "thread", "value": "12680-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_fixture_zcc"}]}